name: Gerar Contribution Snake

permissions:
  contents: write   # permite que o Actions faça push no repositório

on:
  push:
  workflow_dispatch:  # permite rodar manualmente pela aba Actions
  schedule:
    - cron: '0 0 * * *'  # executa todo dia às 00:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Faz checkout completo (fetch-depth: 0 para pegar todo o histórico de commits)
      - name: Clonar repositório de perfil
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2) Gera o GIF usando a Action oficial Platane/snk@v3
      - name: Gerar Snake GIF
        uses: Platane/snk@v3
        with:
          # usuário do GitHub cujo gráfico será "comido"
          github_user_name: Fehscudiero
          # caminho onde o GIF será gerado
          outputs: |
            dist/github-contribution-grid-snake.gif

      # 3) Comita o GIF gerado de volta no branch principal
      - name: Commitar GIF gerado
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # adiciona o GIF que está dentro de dist/
          git add dist/github-contribution-grid-snake.gif
          # só faz commit se houver mudança
          if git diff --cached --quiet; then
            echo "Nenhuma mudança no GIF — pulando commit"
          else
            git commit -m "Atualizar contribution-snake"
            git push origin HEAD:main
          fi
