name: Gerar Contribution Snake

on:
  schedule:
    - cron: '0 0 * * *'    # executa diariamente às 00:00 UTC
  workflow_dispatch:      # permite disparo manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório de perfil
        uses: actions/checkout@v3
        with:
          repository: Fehscudiero/Fehscudiero
          path: perfil

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Instalar dependências do snk
        working-directory: perfil
        run: |
          npm install @platane/snk

      - name: Gerar GIF da cobra
        working-directory: perfil
        run: |
          npx snk --username=Fehscudiero --output=github-contribution-grid-snake.gif

      - name: Commitar GIF gerado
        working-directory: perfil
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add github-contribution-grid-snake.gif
          git commit -m "Atualizar contribution-snake" || echo "Nenhuma alteração detectada"
          git push origin HEAD:main
