name: Gerar Contribution Snake

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *'   # executa diariamente às 00:00 UTC
  workflow_dispatch:     # permite disparo manual pela aba Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório de perfil
        uses: actions/checkout@v3
        with:
          repository: Fehscudiero/Fehscudiero
          fetch-depth: 0

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Gerar e capturar GIF com npx
        run: |
          # Aqui usamos o parâmetro correto: --github_user_name
          npx -p snk snk --github_user_name Fehscudiero --output=github-contribution-grid-snake.gif

      - name: Commitar GIF gerado
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if git diff --quiet --exit-code github-contribution-grid-snake.gif; then
            echo "Nenhuma alteração detectada no GIF — pulando commit"
          else
            git add github-contribution-grid-snake.gif
            git commit -m "Atualizar contribution-snake"
            git push origin HEAD:main
          fi
